In [ ]:
#numpy package for multidimensional array
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
lists=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(lists)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(29)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [ ]:
np.arange(1,6,2)

array([1, 3, 5])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(9,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros(8,int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.linspace(1,6,2)

array([1., 6.])

In [ ]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.23153788, 0.29154271],
       [0.52909486, 0.11701286],
       [0.31531247, 0.19710865]])

In [ ]:
np.random.randn(3,2)

array([[ 0.02591198,  0.98653356],
       [-1.44157065, -0.29271152],
       [-0.74088781, -0.1743715 ]])

In [ ]:
np.random.randint(1,5)

2

In [ ]:
np.random.randint(34,100,50)

array([89, 56, 71, 88, 83, 73, 60, 88, 91, 50, 64, 42, 57, 85, 99, 46, 89,
       66, 72, 48, 95, 88, 58, 41, 43, 76, 82, 81, 47, 98, 34, 82, 95, 53,
       94, 49, 61, 61, 66, 71, 66, 76, 49, 71, 60, 39, 58, 88, 55, 98])

In [ ]:
samplearray=np.arange(30)

In [ ]:
samplearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,20)

In [ ]:
rand_array

array([63, 65, 33, 40, 72, 46, 41, 42, 59, 81, 26, 21,  7, 11, 15, 81, 74,
       87, 37, 59])

In [ ]:
samplearray.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

7

In [ ]:
rand_array.argmin()

12

In [ ]:
a=np.eye(5)

In [ ]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
samplearray=np.arange(10,21)

In [ ]:
samplearray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
samplearray[3]

13

In [ ]:
samplearray[4]

14

In [ ]:
samplearray[3:7]

array([13, 14, 15, 16])

In [ ]:
samplearray[1:3]

array([11, 12])

In [ ]:
samplearray[1:4]=100

In [ ]:
samplearray

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
samplearray=np.arange(10,21)
samplearray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
samplearray[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset=samplearray[0:7]
subset

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
samplemat=np.array([[23,26,35,14],[26,69,54,87],[65,58,47,12]])
samplemat

array([[23, 26, 35, 14],
       [26, 69, 54, 87],
       [65, 58, 47, 12]])

In [ ]:
samplemat[0:2,2]

array([35, 54])

In [ ]:
samplemat[2,:]

array([65, 58, 47, 12])

In [ ]:
samplemat[:,(3,2)]

array([[14, 35],
       [87, 54],
       [12, 47]])

In [ ]:
samplemat=np.arange(1,20)

In [ ]:
samplemat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
samplearray+samplearray

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
np.exp(samplearray)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [ ]:
np.sqrt(samplearray)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [ ]:
np.log(samplearray)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227])

In [ ]:
np.max(samplearray)

20

In [ ]:
np.min(samplearray)

10

In [ ]:
np.argmin(samplearray)

0

In [ ]:
np.square(samplearray)

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [ ]:
np.std(samplearray)

3.1622776601683795

In [ ]:
np.var(samplearray)

10.0

In [ ]:
np.mean(samplearray)

15.0

In [ ]:
array=np.random.randn(3,4)

In [ ]:
array

array([[ 1.0561871 ,  0.13481891,  2.13976682, -0.68144614],
       [-0.33950593,  0.40097369,  0.01576653,  0.08243329],
       [-0.19697674, -0.58590339,  0.73012323, -0.12086047]])

In [ ]:
np.round(array,decimals=3)

array([[ 1.056,  0.135,  2.14 , -0.681],
       [-0.34 ,  0.401,  0.016,  0.082],
       [-0.197, -0.586,  0.73 , -0.121]])

In [ ]:
sports=np.array(['golf','cricket','fball','cricket'])
sports

array(['golf', 'cricket', 'fball', 'cricket'], dtype='<U7')